version: 2.1
jobs:
  build:
    docker:
      - image: node:21.5.0
    steps:
      - checkout
      - run: npm install

  test:
    docker:
      - image: node:21.5.0
    steps:
      - checkout
      - run: npm install
      - run: npx playwright install
      - run: npm test

workflows:
  version: 2
  build-and-test:
    jobs:
      - build
      - test:
          requires:
            - build
