version: 2.1
jobs:
  build:
    docker:
      - image: circleci/node:21.5.0
    steps:
      - checkout
      - run: npm install

  test:
    docker:
      - image: circleci/node:21.5.0
    steps:
      - checkout
      - run: npm install
      - run: npm test
