version: 2.1
jobs:
  build:
    docker:
      - image: circleci/node:17.2-stretch-browsers
    steps:
      - checkout
      - run: npm install

  test:
    docker:
      - image: circleci/node:17.2-stretch-browsers
    steps:
      - checkout
      - run: npm install
      - run: npm test
